version: '3'

services:
  app:
    build: .
    dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "mongodb://mongo:27017"
      REDIS_URL: "redis://redis:6379"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  mongo:
    image: mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  volumes:
    mongo_data:
